### ISSUE TITLE
В epf папка ЗагрузитьПердприятие выглядит неблагозвучно

### ISSUE THREAD

**Issue by EvilBeaver** [silverbulleters/vanessa-runner#1]
Надеюсь, что это просто опечатка, в боевом проекте иметь такое некрасиво :smile:

**Comment by pumbaEO** [comment]
Ну если более подробно, то это "ЗакрытьПредприятиеПослеОбновления" или лучше наверное "exitafterbaseupdate".

**Comment by EvilBeaver** [comment]
Женя, ПЕРДприятие - это какое-то нехорошее ПРЕДприятие?

**Comment by pumbaEO** [comment]
Замулился глаз, исправлю. 
p.s.: но, если оно модально, требует обязательно реакции пользователя, то ...
