### ISSUE TITLE
init-dev и update-dev - обновление конфигурации базы данных

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-runner#10]
Было бы круто, если бы init-dev и update-dev сразу обновлял конфигурацию БД

**Comment by pumbaEO** [comment]
имхо init-dev как раз нужна только конфа, обновленная база я как бы и не предполагал использовать. Т.е. ibservice мне необходима тупо для выгрузке/загрузке внешних обработок или же расширений на правильных метаданных. 
Просто init - тут согласен можно добавить или же просто в bat добавить запуск update

**Comment by pumbaEO** [comment]
Исправил.
