### ISSUE TITLE
Ожидание завершения "Начальное заполнение данных" в обработке "ЗакрытьПредприятие"

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-runner#12]
Во многих типовых конфигурациях при первом запуске вылезает форма "Начальное заполнение данных". Было бы хорошо, если бы обработка ждала пока эта форма отработает.
У нас в скриптах есть специальный шаг, который запускает приложение и ждет пока начальное заполнение данных отработает. Хотел бы перевести и его на VR

**Comment by artbear** [comment]
Такой шаг довольно давно реализован.
Посмотри ЗакрытиеПредприятие.epf

@viskvortsov сообщи, устроил тебя реализованный вариант закрытия?

**Comment by artbear** [comment]
@viskvortsov Обнаружил, что начальное заполнение все-таки не работает.
Исправил.
Сейчас буду заливать исправляющий PR

И далее в ближайшее время выпустим релиз
