### ISSUE TITLE
Версия 0.10 игнорирует ключ --ordinaryapp 0

### ISSUE THREAD

**Issue by EvilBeaver** [silverbulleters/vanessa-runner#123]
После обновления на последнюю версию runner шаг запуска xunit стал игнорировать ключ --ordinaryapp и запускает толстый управляемый клиент (что валит тесты).

При наличии этого ключа должен запускаться 1Cv8c.exe, вместо 1Cv8.exe

**Comment by artbear** [comment]
Приведи свою строку запуска `runner xunit`

**Comment by EvilBeaver** [comment]
```bat
set CICD_TOOLS=C:/CICD

call runner xunit "%WORKSPACE%/build" --ibname "/F%CD%/.packman/v8r_TempDB" --reportsxunit "ГенераторОтчетаJUnitXML{%WORKSPACE%/.packman/init-db.xml}" --pathxunit %CICD_TOOLS%/xUnit/4.0/xddTestRunner.epf
```

**Comment by EvilBeaver** [comment]
В отладочном логе v8runner запускается толстый клиент. По коду, вроде бы все ок.

**Comment by EvilBeaver** [comment]
хм.. видимо это я продолбал... Ключа-то и нет )))

**Comment by artbear** [comment]
переходи на json-файлы настройки
очень удобно.
смотри пример в ридми ветки девелоп

**Comment by EvilBeaver** [comment]
я перехожу на предметно-ориентированные классы внутри пайплайнов. Но "перехожу" слишком смелый термин. "Медленно переползаю" - будет вернее.

**Comment by artbear** [comment]
это как? можешь здесь или в гиттере привести примеры, связанные с 1С или оскриптом ?
