### ISSUE TITLE
Синтаксический контроль

### ISSUE THREAD

**Issue by ondimon** [silverbulleters/vanessa-runner#126]
Приветствую.
На данный момент для синтаксического контроля используется процедура `ВыполнитьСинтаксическийКонтроль` библиотеки `v8runner`, может лучше использовать процедуру `ВыполнитьРасширеннуюПроверкуКонфигуратора` для того, чтобы была возможность передавать дополнительные ключи, например  -ExternalConnectionServer или -ThickClientServerOrdinaryApplication

**Comment by ondimon** [comment]
Я уже переделал на использование `ВыполнитьРасширеннуюПроверкуКонфигуратора`, есть ли какие то требования? или могу заслать пулл реквест?

**Comment by artbear** [comment]
Да, присылай пулл-реквест.
Главное, чтобы тесты/фичи проходили
запусти `1bdd ./features` в каталоге проекта

**Comment by artbear** [comment]
Спасибо, отличное предложение по пулл-реквесту.
Жду

**Comment by artbear** [comment]
Выполнено в #128
Я добавил доп.описание из СП Конфигуратора
