### ISSUE TITLE
Возможность запуска произвольных команд на базе задач (tasks)

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#127]
Было бы удобно выполнять произвольные команды через
`runner task ИмяКоманды` аналогично `opm tasks`

где `ИмяКоманды` - имя скрипта из вложенного каталога `tasks`

Например, при работе с фичей или тестом для 1С из VSC хочется быстро запустить Предприятие с запуском Ванессы или хЮнит с передачей на выполнение только одного текущего файла

При этом не хочется добавлять отдельный класс продукта для такой небольшой задачи

@nixel2007 @EvilBeaver @pumbaEO Что скажете?

**Comment by nixel2007** [comment]
Почему не использовать таски из опм?

**Comment by artbear** [comment]
Потому что забывчивость и отсутствие доки на `opm tasks` :)

**Comment by pumbaEO** [comment]
Через opm уже все будет работать, в runner имхо это лишнее.

**Comment by artbear** [comment]
Да, я забыл закрыть
