### ISSUE TITLE
vrunner syntax-check отсутствуют параметры --db-user --db-pwd

### ISSUE THREAD

**Issue by ramzesvvsu** [silverbulleters/vanessa-runner#131]
Когда я выполняю команду
vrunner syntax-check --junitpath out/junitscheck.xml --ibname /s"server\database" --mode -ThinClient --db-user username --db-pwd password
В проверяемую базу данных не передаются параметры --db-user username --db-pwd password

При проверке выходит ошибка
30.07.2017 14:52:19: ИНФОРМАЦИЯ - Выполняю синтакс-контроль конфигурации
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
30.07.2017 14:52:38: ИНФОРМАЦИЯ - Результат синтакс-контроля: Пользователь ИБ не
 идентифицирован

**Comment by pumbaEO** [comment]
https://github.com/silverbulleters/vanessa-runner/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0.os#L359 
В 0.14.0 сделанно.

**Comment by ramzesvvsu** [comment]
Проблема осталась.
Добавляем перед строчкой 
https://github.com/silverbulleters/vanessa-runner/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0.os#L359

    Сообщить("Логин");  
    Сообщить(ДанныеПодключения.Пользователь);   

И получаем вывод
D:\Repository\gitsync\workspace\test_ugsk_dev>vrunner version
0.14.0

D:\Repository\gitsync\workspace\test_ugsk_dev>vrunner syntax-check --junitpath o
ut/junitscheck.xml --ibname /s"10.126.123.13\test" --mode -ThinClient --db-user
login --db-pwd pass
vanessa-runner v0.14.0
23.08.2017 20:37:31: ПРЕДУПРЕЖДЕНИЕ - ------------------------------------------
------------------------
23.08.2017 20:37:31: ПРЕДУПРЕЖДЕНИЕ - Параметр --ibname устарел. Используйте --i
bconnection вместо него!
23.08.2017 20:37:31: ПРЕДУПРЕЖДЕНИЕ - ------------------------------------------
------------------------
23.08.2017 20:37:31: ИНФОРМАЦИЯ - Выполняю синтакс-контроль конфигурации
Логин

^CTerminate batch job (Y/N)? y

А ожидается что должна была выйти строка с логином

**Comment by pumbaEO** [comment]
Если выполнить команду runner help syntax-check, то в конце про параметр --mode будет такая фраза: *ВНИМАНИЕ, ВАЖНО: этот параметр --MODE должен быть последним среди параметров!*

Правильная строка получается:
```
vrunner syntax-check --junitpath o
ut/junitscheck.xml --ibname /s"10.126.123.13\test" --db-user
login --db-pwd pass --mode -ThinClient
```
