### ISSUE TITLE
Запуск opm install в каталоге автоматом начинает собирать обработки, зачем?

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/vanessa-runner#135]
На этапе определиния простейших зависимостей, сразу запускается сборка внешних обработок. Если стоит голый оскрипт и опм, то все ломается. А если вдруг нет 1С, то также все ломается.

Почему бы не сделать отдельную задачу в tasks/build.os и там запускать запуск, при этом в tasks/test.os прописать запуск отдельно opm run build ?

**Comment by artbear** [comment]
А зачем запускать `opm install в каталоге` ? для чего?
+ приведи, плиз, полный текст `opm install`
+ приведи сценарий работы

**Comment by nixel2007** [comment]
opm install устанавливает текущие зависимости по описанию в packagedef

**Comment by pumbaEO** [comment]
https://github.com/silverbulleters/vanessa-runner/pull/136
исправляет проблему. 

```
 ~/projects/evilveaver/vanessa-runner   develop  opm install 
vanessa-runner v0.12.0

02.08.2017 11:58:09: ИНФОРМАЦИЯ - Собираю внешние обработки из исходников в epf, назначение epf
No bp log location saved, using default.
02.08.2017 11:58:21: ИНФОРМАЦИЯ - Сборка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - logos уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: cmdline
ИНФОРМАЦИЯ - cmdline уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
ИНФОРМАЦИЯ - tempfiles уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: asserts
ИНФОРМАЦИЯ - asserts уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: v8runner
ИНФОРМАЦИЯ - v8runner уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - strings уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: json
ИНФОРМАЦИЯ - json уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: 1commands
ИНФОРМАЦИЯ - 1commands уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: 1bdd
ИНФОРМАЦИЯ - 1bdd уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: fs
ИНФОРМАЦИЯ - fs уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: ParserFileV8i
ИНФОРМАЦИЯ - ParserFileV8i уже установлен. Пропускаем.
```

**Comment by artbear** [comment]
Проблема, с которой ты столкнулся, мне все равно непонятна.

>А зачем запускать `opm install в каталоге` ? для чего?
> + приведи, плиз, полный текст `opm install`
> + приведи сценарий работы

Ответ я не получил

**Comment by artbear** [comment]
`projects/evilveaver/vanessa-runner`

`evilveaver` ? :)

**Comment by pumbaEO** [comment]
Еще раз чистая установка, есть только oscript собранный и opm, что-бы поставить хоть какие-то зависимости, а не руками перебирать для пакета достаточно в его каталоге выполнить opm install . Сейчас в этой команде почему-то лезет сборка каких-то непонятных epf. Зачем любое получение информации о пакете из файла packagedef выполнять код?

**Comment by artbear** [comment]
На мой взгляд все логично.
+ Ты выполняешь команду "Установить мне ванесса-раннер"
+ Ванесса-раннер берет под козырек и устанавливает продукт как будто с нуля
  + при нулевой установке продукта у тебя нет собранных epf-файлов
  + а для работы продукта эти файлы требуются
+ поэтому ванесса-раннер их и собирает 

А вот вопрос `Зачем на любое получение информации о пакете из файла packagedef выполнять код?` нужно переадресовать уже в opm, сказав "Привет, Никита :)"

**Comment by nixel2007** [comment]
я-то чо, это ты сам запихнул это в packagedef.
готовлю обновление opm

**Comment by artbear** [comment]
а я-то чо (с) - я ведь спрашивал совет и получил его перед текущей реализацией в packadef :)

**Comment by artbear** [comment]
Исправлено
