### ISSUE TITLE
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated

### ISSUE THREAD

**Issue by russinow** [silverbulleters/vanessa-runner#144]
практически чистая система win10 с самыми последними обновлениями, установка через команду "opm install vanessa-runner". При каждом вызове команды "runner" появляется такое сообщение: "WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context" первой строкой, а после собственно вывод команды.
Не критично, но неприятно.

**Comment by nixel2007** [comment]
@russinow необходимо обновить имеющиеся библиотеки. `opm update -all`

**Comment by ViktorErmakov** [comment]
> @russinow необходимо обновить имеющиеся библиотеки. `opm update -all`

не помогает мне и сейчас. 
Все равно выходит такая же надпись.

**Comment by artbear** [comment]
Движок 1скрипт у тебя сейчас какой?
oscript -version

**Comment by ViktorErmakov** [comment]
1.1.0.325
