### ISSUE TITLE
поставка и обновление через opm

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-runner#15]
очень хочется следующий цикл для стабильного ранера
- git push master
- POST hub.oscript.io
- opm install vanessa-runner
- vrunner --help

**Comment by nixel2007** [comment]
Нужно помочь @EvilBeaver развернуть мой скрипт на его ci

**Comment by artbear** [comment]
ИМХО все готово для выгрузки на хаб.
Предлагаю выгрузить на хаб оскрипта.

**Comment by pumbaEO** [comment]
Тогда надо или включать обработки как бинари или же исключить внешние обработки из сборки opm, там ведь они не нужны.

**Comment by artbear** [comment]
насколько я понимаю, после установки пакета он должен быть рабочим.
ИМХО runner не будет рабочим без этих обработок.
Верно?

**Comment by nixel2007** [comment]
почему нельзя включить как бинари? тем более у opm есть возможность выполнить пред-упаковочный скрипт.

**Comment by pumbaEO** [comment]
Эти обработки, они только для конфигурация на базе БСП предназначены.

**Comment by nixel2007** [comment]
@pumbaEO ну, вызывать их или нет - это уже на совести конечного пользователя. Большинство конфигураций базируется на БСП.

**Comment by pumbaEO** [comment]
Если они будут бинарниками, тогда как их пользователь будет искать где-то где opm поставит, имхо будет еще больше вопросов.

**Comment by EvilBeaver** [comment]
я может не в теме.. эти обработки они же входят в состав раннера и запускаются им? Тогда зачем пользователю вообще знать про эти обработки. В packman тоже есть внешняя обработка, но она запускается только пакманом и пользователю нет дела до того, куда ее ставит opm.

**Comment by pumbaEO** [comment]
Они рядышком, например эти обработки я с помощью деплойки запускаю, после обновления базы, что-бы подгрузить внешние обработки и расширения.

**Comment by nixel2007** [comment]
А, я понял в чем проблема - раннеру они передаются по пути. Может добавить в раннер команды для их вызова? Типа `runner run -confirmLegality``

**Comment by artbear** [comment]
Может быть, механизм тасков, аналогично opm, реализовать для раннера?
для запуска подобных задач?

**Comment by nixel2007** [comment]
Не подойдёт. Opm run выполняется в контексте CWD, а раннер обычно запускается из проекта, где сама конфигурация лежит

**Comment by artbear** [comment]
А какая разница? раннер будет таски брать из своего каталога, а не из текущего!

**Comment by nixel2007** [comment]
@artbear профит-то в чем? Не описывать 5 комманд, а сделать универсальный запускатор? Стоит оно того?

**Comment by artbear** [comment]
Расширяемость, плагинность :)

**Comment by artbear** [comment]
На чем остановились?
ИМХО распространять нужно в виде opm в полной поставке - весь набор скриптов + нужные бинарники.
для CI я пока юзаю `git clone'

А вообще хочется сильно упростить код, разнеся код команд и код исполняемого приложения на разные файлы скриптов, аналогично шаблону по созданию приложений https://github.com/EvilBeaver/oscript-app-template

**Comment by artbear** [comment]
А как epf в пакет включил?

**Comment by nixel2007** [comment]
как каталог. в котором лежат исходники обработок.

**Comment by artbear** [comment]
Нужно решить, как будем распространять через opm ? 

Остался единственный вопрос - что делать с бинарниками (1С-файлы, v8unpack) ?
/cc @pumbaEO @nixel2007 @allustin 

Мне нужно в рамках текущего проекта.

**Comment by pumbaEO** [comment]
имхо, 1с файлы там не нужны, их наверное правильней в отдельный репо выделить, ведь код там для SSL-based конфигураций.

**Comment by artbear** [comment]
мне для наших проектов нужно использовать установку раннера на агентах ТФС, нужен как раннер, так и бинарники 1С.
Хотелось бы через opm или еще как-то получать готовый раннер + собранные внешние обработки.
Каким образом это можно сделать?

@allustin @nixel2007 @pumbaEO Давайте уже договоримся и реализуем любой из вариантов.
Готов доработать.

**Comment by nixel2007** [comment]
Варианты:
* Положить собранные epf в репо
* Пре-билд скрипт для opm build
* Кастомный билдер с собственным пребилдом и вызовом opm build.

Мне больше нравится второй вариант.

15 февраля 2017 г., 10:36 пользователь Artur Ayukhanov <
notifications@github.com> написал:

**Comment by dmpas** [comment]
Мне кажется, я по адресу жалуюсь:
`Команда.УстановитьСтрокуЗапуска("oscript tools\runner.os compileepf ./epf ./epf");`

при сборке пакета под убунтой вот эта ваша строчка из `packagedef` ломается.

**Comment by artbear** [comment]
просто без `.` будет достаточно?
`Команда.УстановитьСтрокуЗапуска("oscript tools\runner.os compileepf epf epf");`

**Comment by dmpas** [comment]
Дело в слэше, я думаю. Не знаю, заработает ли после этого, просто в логах увидел сообщение и побежал ябедничать.

**Comment by artbear** [comment]
Спасибо.
Тесты прошли. Запушил в девелоп.

**Comment by artbear** [comment]
Реализовано в 0.10.0
