### ISSUE TITLE
vanessa-runner xunit работает неверно, если явно передан несуществующий файл настройки

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#168]
`vanessa-runner xunit` работает неверно, если явно передан несуществующий файл настройки
Например, 
`vanessa-runner xunit --settings dummy.json` не выдает ошибок отсутствия файла, но использует настройки по умолчанию
Проверено на версии `v0.14.0`

Пример лога
```
15:17:15 c:\j\workspace>vanessa-runner xunit --settings dummy.json --ibconnection /F./build/ibservice 
15:17:15 vanessa-runner v0.14.0
15:17:16 15.09.2017 15:17:16: ИНФОРМАЦИЯ - Выполняю тесты %1
```

**Comment by artbear** [comment]
@pumbaEO сможешь исправить?

**Comment by pumbaEO** [comment]
Странно, именно --settings  не работает? 
https://github.com/silverbulleters/vanessa-runner/blob/develop/src/main.os#L172 вот передает значение настройки --settings в процедуру
https://github.com/silverbulleters/vanessa-runner/blob/develop/src/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9E%D0%B1%D1%89%D0%B8%D0%B5%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B.os#L165 и проеверка на существование https://github.com/silverbulleters/vanessa-runner/blob/develop/src/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9E%D0%B1%D1%89%D0%B8%D0%B5%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B.os#L177

Должно вернуть пустые настройки.

**Comment by artbear** [comment]
я привел пример боевого кода, из-за которого 1С зависло на ожидании ввода/выбора логина авторизации 1С.

**Comment by nixel2007** [comment]
> Должно вернуть пустые настройки.

так вот по этому и висит, насколько я понимаю.

**Comment by artbear** [comment]
ИМХО если явно указан несуществующий файл настройки, нельзя проглатывать ошибку.
нужно выдавать исключение для пользователя - нафига ты даешь мне неверный файл?
