### ISSUE TITLE
Команда run не интерактивна

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/vanessa-runner#173]
Команда run не выводит интерактивно своего состояния, по сравнению с run в деплойке. Соответственно ее не интересно использовать на ci , т.к. выводит сообщение в конце своей работы, а не по мере поступления данных от процесса.

**Comment by artbear** [comment]
@pumbaEO Решается в https://github.com/silverbulleters/vanessa-runner/pull/244
верно?

**Comment by pumbaEO** [comment]
да
