### ISSUE TITLE
Доработать код работы с хранилищем из-за изменений в v8storage

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#193]
https://github.com/Khorevaa/v8storage/releases/tag/0.6.4
Переименованы функции, которые используются в раннере

@Khorevaa  ты меняешь свое API и ломаешь совместимость, а отмечаешь изменения только в patch-номере :(
нехорошо :( 

ладно, хоть я зашел и почитал изменения в релизе.
иначе был бы сюрприз для пользователей ванесса-раннер!
я бы выпустил версию 0.7.0 для этого

**Comment by artbear** [comment]
CI сейчас падает именно из-за этого
http://ci.silverbulleters.org/job/Vanessa-runner/job/develop/lastCompletedBuild/consoleFull
```
ИНФОРМАЦИЯ - Выполняю создание пользователя хранилища конфигурации
17:04:50 КРИТИЧНАЯОШИБКА - 
{Модуль C:\cicd\workspace\Vanessa-runner_develop
QMF2XLOCAPVNBGZY6TVHLNWTPUR6NAPQUNBIN3JDPZYKWTF2Y64Q\
src\Классы\КомандаСоздатьПользователейХранилища.os / 
Ошибка в строке: 93 / {
Модуль C:\cicd\workspace\Vanessa-runner_develop
QMF2XLOCAPVNBGZY6TVHLNWTPUR6NAPQUNBIN3JDPZYKWTF2Y64Q\
src\Классы\МенеджерКонфигуратора.os / 
Ошибка в строке: 336 / Метод объекта не обнаружен (УстановитьКаталогХранилища)}    
17:04:50 	ХранилищеКонфигурации.УстановитьКаталогХранилища(ПутьХранилища);
```

**Comment by nixel2007** [comment]
0.x.x - имеет право делать все, что хочет.
Это твоя обязанность как потребителя 0.x библиотеки следить за ее API

**Comment by artbear** [comment]
про `имеет право` не совсем согласен.
ломание совместимости все-таки достойно более серьезной правки версии.

**Comment by nixel2007** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by artbear** [comment]
Исправлено

**Comment by khorevaa** [comment]
@artbear @nixel2007 Слудующий раз учту.
