### ISSUE TITLE
syntax-check падает с ошибкой, если в ключе --junitpath указать директорию, которая не существует

### ISSUE THREAD

**Issue by leemuar** [silverbulleters/vanessa-runner#194]
Допустим каталога out/ не существует

Когда я выполняю команду
```
vrunner syntax-check --ibconnection "/FC:\Users\usr\Documents\InfoBase" --junitpath out/syntax-check.xml --mode -ThinClient -Server
```

тогда получаю ошибку

```
vanessa-runner v0.17.0
02.12.2017 17:00:37: ИНФОРМАЦИЯ - Выполняю синтакс-контроль конфигурации
02.12.2017 17:00:39: ИНФОРМАЦИЯ - Результат синтакс-контроля: Ошибок не обнаружено

02.12.2017 17:00:39: КРИТИЧНАЯОШИБКА - {Модуль D:\Apps\OneScript\lib\vanessa-runner\src\Классы\КомандаПроверкаСинтаксиса.os / Ошибка в строке: 163 / Внешнее исключение (System
.IO.DirectoryNotFoundException): Не удалось найти часть пути "D:\workspace\git\trade\out\syntax-check.xml".}
```

и файл с результатами проверки отсутствует по указанному пути

Хотелось бы чтобы файл из ключа --junitpath команды syntax-check создавался даже если такой директории не существует на момент запуска команды

**Comment by artbear** [comment]
Нет, как раз каталоги должны создаваться самостоятельно.
Вдруг пользователь ошибся и указал неверный путь или вообще его не указал.
Пусть сам создает каталог

Да, на CI это доставляет проблемы, т.к. приходится добавлять шаг с созданием каталога.

@pumbaEO @nixel2007 что скажете?

**Comment by leemuar** [comment]
Такое поведение расходится с поведением других утилит, которые файл создают без лишних вопросов.
Если нужна ошибка при отсутствии каталога - может управлять этим доп ключом? По умолчанию файл создавать, но если передан спецключ (например, --failOnDirNonexist) - выходить с ошибкой, если каталога не существует.

**Comment by leemuar** [comment]
Если пользователь не указал файл - имхо об этом нужно сообщать прямо и ДО выполнения команды

**Comment by TheDemonCat** [comment]
@artbear Походу нужно воскресить ишуз, так как проблема не была решена.
