### ISSUE TITLE
init-dev не добавляет созданную базу в список баз 1С

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#197]
выполнил `vrunner init-dev`
база создана, а при запуске 1С ее не видно.
приходится вручную создавать.

@pumbaEO Подскажешь, что не так?

**Comment by pumbaEO** [comment]
Удобно таки. А логи, что говорят? Там должно предупреждение вывестись, если не смогло записать файл баз.

**Comment by artbear** [comment]
Да, было такое сообщение.
посчитал его за уже привычный баг при обновлении на 19 и 20 релиз движка :(
