### ISSUE TITLE
На заглавной странице упомянута deployka

### ISSUE THREAD

**Issue by EvilBeaver** [silverbulleters/vanessa-runner#2]
Этот инструмент, во-первых, не опубликован, во-вторых, запускаться должен не через технический файл console-entry-point, а через deployka.bat(sh)

Т.е. задумано вот так:

    deployka loadrepo %DATABASE% %STORAGEPATH% -storage-user base -storage-pwd "234567890" -v8version %VERSION%

И т.д.

Цель issue - выработать идеологию правильного использования deployka

**Comment by allustin** [comment]
@pumbaEO поторопились с документацией. @EvilBeaver щас уберем ;-) - предлагаю деплойку пока обсуждать в закрытом режиме. Я тут на май готовлю к запуску контура для 1С-ников "внаем" с поддержкой - в рамках vanessa.services - поэтому пока скрываем.
