### ISSUE TITLE
CI продукта (Jenklinsfile) выдает ошибку сборки

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#201]
CI продукта (Jenklinsfile) выдает ошибку сборки
Например, http://ci.silverbulleters.org/blue/organizations/jenkins/Vanessa-runner/detail/PR-200/1/pipeline

Проблема в том, что в Jenklinsfile выполняется команда `opm update -all`
```
opm update -all 
...
ИНФОРМАЦИЯ - Устанавливаю пакет opm

КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\Классы\УстановкаПакета.os 
/ Ошибка в строке: 91 
/ Ошибка установки пакета <opm>: Обнаружена устаревшая версия движка OneScript.

Требуемая версия: 1.0.19

Текущая версия: 1.0.17.95

Обновите OneScript перед установкой пакета}

script returned exit code 255
```

@nixel2007 Подскажи, как лучше и проще исправить проблему?
+ переустановить движок на ноде на 19 или 20 релиз ?
  + и затем использовать `opm install -l` ?
+ или вообще убрать `opm update -all` ?

**Comment by nixel2007** [comment]
Убрать -all.

**Comment by nixel2007** [comment]
vrunner должен запускаться на минимальной требуемой версии движка.

**Comment by artbear** [comment]
Ага, сборка поехала дальше
