### ISSUE TITLE
Ошибка тестирования, если на машине установлены платформы 8.3.10 и старше (8.3.11 или 8.3.12)

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#204]
Ошибка тестирования, если на машине установлены платформы 8.3.10 и старше (8.3.11 или 8.3.12)

При прогоне тестов `vanessa-runner` или выполнении `opm build .` получаем ошибку
```
ОШИБКА - {Модуль C:\OneScript\lib\v8runner\src\v8runner.os / Ошибка в строке: 1109 / 
Для работы с информационной базой необходима версия платформы не меньше, чем 8.3.11.
Текущая версия 8.3.10.2650.
Для работы с информационной базой необходима версия платформы не меньше, чем 8.3.11.
Текущая версия 8.3.10.2650.
}
```
проблема в явном указании в packagedef
`Команда.УстановитьСтрокуЗапуска("oscript tools/runner.os compileepf epf epf --v8version 8.3.10");`

**Comment by nixel2007** [comment]
да чо баг-то, е-мое

**Comment by artbear** [comment]
падает потому-что :(

**Comment by artbear** [comment]
Проблема была в явном указании 8.3.10 при сборке
`Команда.УстановитьСтрокуЗапуска("oscript tools/runner.os compileepf epf epf --v8version 8.3.10");`
