### ISSUE TITLE
Команда run: не выводится лог работы 1С:Предприятие

### ISSUE THREAD

**Issue by ImHunter** [silverbulleters/vanessa-runner#207]
Вижу только результат "ИНФОРМАЦИЯ - Информации об ошибке нет".
Хотелось бы, как в Деплойке, видеть весь лог работы Предприятия.
Попробую сам найти и предложить какое-то решение. Но может я чего-то упустил, и это можно сделать каким-то готовым способом?

**Comment by ImHunter** [comment]
Вообще, мне это нужно, чтобы определить параметры конфигурации:
- соответствует ли конфигурация конфе БД
- версия платформы
- версия конфигурации
Для этого служебная обработка через Сообщить выводит нужные данные. Потом лог разбираю и определяю эти параметры. Может каким-то другим способом это можно определить?

**Comment by ImHunter** [comment]
Вроде сам разобрался. Лог предприятия НЕ выводится, если в ключах запуска есть /RunModeManagedApplication.
Немного дописал Ванессу, чтобы можно было вообще не передавать этот параметр. Дописано аккуратно - ранее работавшую логику не порушит.
Еще потестирую и позже выложу.

**Comment by artbear** [comment]
Выполнено в #208
