### ISSUE TITLE
Использование v8unpack

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#21]
Сейчас нигде в документации не сказано про `v8unpack`
В итоге запуск `decompileepf` завершается со странной ошибкой.

Нужно 
+ или каким-то образом положить v8unpack в репозитарий продукта
+ или документировать, что v8unpack должен быть установлен ранее и д.находиться по пути из Path

**Comment by pumbaEO** [comment]
я за документацию. Сейчас runner работает без проблем и в linux и window , если куда-то еще v8unpack пихать, тогда будет не кроссплатформенно.

**Comment by artbear** [comment]
Еще предлагаю добавить проверку существования `v8unpack` перед запуском основной программы.
Например, просто вызов `v8unpack` и проверка отсутствия ошибки `The system cannot find the file specified` или `Не удается найти указанный файл`
