### ISSUE TITLE
Нужен спец.параметр внутри параметров json, указывающий на путь к vanessa-runner и/или add

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#220]
Сценарий:
+ нужно запустить дымовые тесты add через vanessa-runner
+ настройки запуска в json находятся в рабочем каталоге
+ но сами дымовые тесты находятся не в рабочем каталоге, а в OneScript/add
+ хотелось бы задать настройку в виде `testpath` : "$runner_root\..\add\tests\smoke"
+ и ванесса-раннер вместо `$runner_root` подставил бы путь к каталогу vanessa-runner

@pumbaEO Какие варианты еще есть?

**Comment by pumbaEO** [comment]
Вот я сейчас не понял где и что хранить собираетесь и для кого. 
"но сами дымовые тесты находятся не в рабочем каталоге, а в OneScript/add" к єтому пути можно добратся относительно чего-либо? "../../../OneScript"
хотелось бы задать настройку в виде testpath : "$runner_root..\add\tests\smoke" - кто потребитель? Сам runner? Речь идет про файл env.json?

**Comment by artbear** [comment]
@pumbaEO Извини, был в командировке, вообще некогда было.

>>но сами дымовые тесты находятся не в рабочем каталоге, а в OneScript/add
>к єтому пути можно добратся относительно чего-либо? "../../../OneScript"

Добраться как-то, конечно, можно, но только в коде
Только в json-файле не от чего оттолкнуться.
+ Есть текущий каталог, откуда запускаем скрипт
+ Есть переменная `$workspaceRoot`, которая обозначает каталог проекта

нет никакой переменной, которую можно заюзать внутри настроечного json-файла, чтобы обратиться к каталогу установки `vanessa-runner` или `add`.

Есть переменная `$runnerRoot`, возвращающая путь ванесса-раннер, но она юзается только при запуске 1С:Предприятия через `vrunner run`, а в других командах переменная не юзается.

Я вообще предлагаю добавить еще переменные для json:
+ `$runnerRoot` - соответствует каталогу установки, например,  `oscript/lib/vanessa-runner`
+ `$oscriptRoot` - всегда `oscript/bin`
+ `$oscriptLibRoot` - всегда `oscript/lib`

@pumbaEO @nixel2007 @EvilBeaver Что скажете?

**Comment by artbear** [comment]
>Нельзя привязываться к каталогу либ, их может быть несколько. 

По либам принято, согласен.

>А чем не устраивают имеющиеся в add функции по получению путей к бдд/тдд? Они же уже реализованы и используются

Тем, что эти функции нельзя в json-файле юзать.

В целом, я уже реализовал PR #222
