### ISSUE TITLE
vrunner load  открывается конфигуратор - это бага или фича?

### ISSUE THREAD

**Issue by AlexStrizh** [silverbulleters/vanessa-runner#232]
При работе в TeamCity становится проблемой открытие окна конфигуратора после загрузки cf в конфу. Из-за этого "зависает" процесс.

Пример:
Starting: C:\Windows\system32\cmd.exe /c vrunner load --settings C:\deploying-db-1c\build\ut_10_3\env.json --src C:\TeamCity\buildAgent\work\2b35ac7e0452d98f\cf\1Cv8.cf --ibconnection /SAAPP03:1741\ut_auto_test --v8version 8.2.19.83

env.json
{
    "default": {
        "--db-user": "впарвпрва",
        "--db-pwd": "ывапывапывап",
        "--ordinaryapp": "1",
        "--storage-name": "\\\\10.10.254.196\\repos\\UT",
		"--storage-user": "впарвпарвапр",
		"--storage-pwd": "вапрвпарвпар"
    }
}

Как подавить открытие окна? Что заставляет его открывать (под капотом еще не смотрел)?

При этом следующая конструкция работает как надо.
"C:\Program Files (x86)\1cv82\8.2.19.83\bin\1cv8.exe" DESIGNER /SAAPP03:1741\ut_auto_test /N"фывафываф" /P"фвыафваыфа" /LoadCfgC:\TeamCity\buildAgent\work\2b35ac7e0452d98f\cf\1Cv8.cf

**Comment by AlexStrizh** [comment]
Открывается окно конфигуратора. Хранилище точно отключено, проверял, так как это было первое предположение. Файл конфигурации успешно загружается, но зачем открывается окно конфигуратора, не понятно. Возможно прилетают еще флаги какие-то?

В коде вижу вот это
Процедура ЗагрузитьФайлКонфигурации(Знач ПутьКФайлу, Знач СниматьСПоддержки = Истина) Экспорт
что приводит (скорее всего, так как проверить сейчас не могу) к добавлению следующих параметров:

ПараметрыЗапуска.Добавить("/ConfigurationRepositoryUnbindCfg -force");
Конфигуратор.ВыполнитьКоманду(ПараметрыЗапуска);

ПараметрыЗапуска = Конфигуратор.ПолучитьПараметрыЗапуска();
ПараметрыЗапуска.Добавить("/ManageCfgSupport -disableSupport -force");

Могут эти флаги приводить к открытию окна конфигуратора?

**Comment by AlexStrizh** [comment]
Таким образом:
1. Теряется пользователь ИБ из json.
2. По умолчанию vrunner load  запускает загрузку с флагом снятия с поддержки, вызывая открытие окна конфигуратора.

**Comment by asosnoviy** [comment]
8.2.19.83 смущает...

**Comment by AlexStrizh** [comment]
На 8.3.10 повторялась проблема, но уже не уверен, надо завтра прогнать тест для другой платформы.

В любом случае для реального проекта я изменил для себя в исходниках СниматьСПоддержки = Истина на Ложь и в TC через cmd сначала делаю отключение от хранилище, а затем загрузку cf (все через vrunner). Но это костыль.

**Comment by asosnoviy** [comment]
ConfigurationRepositoryUnbindCfg попадается на итс начиная с 8.3.7

**Comment by AlexStrizh** [comment]
Костыль, про который я говорил, отрабатывает на `--v8version 8.2.19.83`, то есть отключение срабатывает `ОтключитьсяОтХранилища.ОтключитьсяОтХранилища()`

**Comment by AlexStrizh** [comment]
Перепроверил на 8.3.10, там проблема не повторяется. Вопрос закрыт. vrunner load для  8.2 работает не так, как ожидается в текущей разработке.
