### ISSUE TITLE
Команды управления сеансами неверно возвращают код успеха в случае различных ошибок работы с ras/rac

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#236]
Видимо, при портировании с deployka не очень точно перенеслось :)

В итоге при запуске в Дженкинсе 2х команд подряд
например,
+ vrunner lock
+ vrunner dbupdate
в случае ошибки в 1й команде выполняются обе команды, хотя это неверно.

@ImHunter @Dumsik вы юзаете управление сеансами из VR ?
На такие проблемы нарывались?

**Comment by Dumsik** [comment]
Вообще с этим проблем небыло.
