### ISSUE TITLE
Подключение к хранилищу выполняется для временной базы, а не для указанной

### ISSUE THREAD

**Issue by Smilebringer** [silverbulleters/vanessa-runner#242]
Ошибка в классе Классы/МенеджерКонфигуратора.os, в процедуре "ПодключитьсяКХранилищу", 
Строка: УправлениеКонфигуратором.СоздатьФайловуюБазу(КаталогВременнойИБ);

**Comment by artbear** [comment]
Еще комментарии в https://github.com/silverbulleters/vanessa-runner/commit/816abae09ca2290fd281bd381ed7e45173fefbfa#r29115575

**Comment by AlexStrizh** [comment]
Костыль:
вместо
//	УправлениеКонфигуратором.СоздатьФайловуюБазу(КаталогВременнойИБ);
//	УправлениеКонфигуратором.УстановитьКонтекст("/F " + КаталогВременнойИБ, "", "");
попробуй
УправлениеКонфигуратором = УправлениеКонфигуратором();

**Comment by artbear** [comment]
@Smilebringer @AlexStrizh посмотрите исправление https://github.com/silverbulleters/vanessa-runner/pull/256

Так устроит?

**Comment by AlexStrizh** [comment]
@artbear Гипотетически это решает проблему.

**Comment by artbear** [comment]
Пока закрываю проблему.
Если возникнет снова, переоткроем
