### ISSUE TITLE
Инкапуслировать валидацию проекта EDT

### ISSUE THREAD

**Issue by VladFrost** [silverbulleters/vanessa-runner#248]
Завернуть в vanessa-runner исполнение `ring edt workspace validate`.
Преобразовать результат из формата CSV в формат JUnit.
Добавить возможность исключений из валидации: эти исключения не должны выдаваться как ошибки в логе, а должны указываться как пропущенные, также эти исключения должны быть указаны как пропущенные в JUnit-файле.

**Comment by artbear** [comment]
Хорошее предложение

**Comment by artbear** [comment]
Выполнено в #258

**Comment by artbear** [comment]
Чтобы осталась ссылка на pipeline Jenkins по проверке EDT
https://gist.github.com/VladFrost/d8c62be2aae85068645adbcb600494b1
