### ISSUE TITLE
Настройки проекта, в котором используется vanessa-runner

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#25]
Сейчас при составлении различных батников для выполнения задач раннера для собственных продуктов приходится сильно дублировать код настроек базы.
Например, в 4 батниках (init, compile,decompile,watch) нужно указывать путь к базе, логин/пароль пользователя, пути к служебным данным и прочее.
Хотелось бы соединить все настройки проекта в едином файле настроек.
И при запуске передавать раннеру указанный файл.

Предлагаю использовать формат json, как простой и удобный.

Нужно договориться о приоритетах между файлом настроек и переменными окружениями.
ИМХО переменные окружения должны быть более приоритетными, чем настройки из файла настроек. Это важно для CI, хотя на CI-серверах можно вообще отключить использование файла настроек.

/cc @allustin @pumbaEO @nixel2007

**Comment by pumbaEO** [comment]
Приоритет:
параметр коммандной строки
переменная окружения
если нашли конфиг файл, тогда берем параметры из конфига.

**Comment by artbear** [comment]
>Приоритет:
>1.  параметр коммандной строки
>1. переменная окружения
>1. если нашли конфиг файл, тогда берем параметры из конфига.

Согласен

**Comment by nixel2007** [comment]
Не совсем понял в каком порядке эти приоритеты :) в целом идея хорошая
