### ISSUE TITLE
Команда createrepo создает всегда пустое хранилище

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/vanessa-runner#255]
Из-за строк https://github.com/silverbulleters/vanessa-runner/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0.os#L476 всегда создаем пустую базу и там создаем хранилище.  Это неправильно, если передали параметры через --ibconnection то необходимо хранилище создавать на базе уже существуюещей БД.

**Comment by artbear** [comment]
Выполнено
