### ISSUE TITLE
Копирование пользователей хранилища

### ISSUE THREAD

**Issue by abirambul** [silverbulleters/vanessa-runner#261]
Есть команда `createrepouser` позволяющая создать нового пользователя хранилища.

В случае, когда существует основное хранилище и необходимо развернуть новое (Технология разветвленной разработки), удобнее использовать копирование пользователей из основного хранилища.

vrunner может копировать пользователей хранилища?

**Comment by artbear** [comment]
Нет, пока не умеет.
Кто бы сделал, это несложно :)
