### ISSUE TITLE
Параметр --online-file - это флаг, хотя вроде как должен быть значением.

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/vanessa-runner#267]
https://github.com/silverbulleters/vanessa-runner/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%97%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B8%D1%82%D1%8C%D0%92%D0%A0%D0%B5%D0%B6%D0%B8%D0%BC%D0%B5%D0%9F%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D1%8F.os#L44

Или я что-то не понимаю, или зачем сейчас параметр --online-file в команде run?
если это флаг, то что он делает?
или он должен быть не флаг?

**Comment by artbear** [comment]
@1cgh Большое спасибо, исправлено.
