### ISSUE TITLE
Неработоспособность сборки при наличии неуправляемых форм

### ISSUE THREAD

**Issue by Infactum** [silverbulleters/vanessa-runner#27]
Если исходная конфигурация содержит неуправляемые формы, то после сборки из исходников формы перестают открываться с ошибкой формата потока.
Для понимания причины рекомендую ознакомиться с [этой статьей](http://infostart.ru/public/250142/) о структуре формата CF. В текущей ситуации файлы неуправляемых форм `form.bin` являются вложенными по отношению к исходной конфигурации и их содержимое не должно быть сжато zlib при упаковке. Vanessa-runner же вызывает `v8unpack` с параметром `- build`, которая всегда зажимает файлы zlib'ом.
Возможные варианты решения:

1. Допилить v8unpack. Благо есть активный разработчик.
2. Замена v8unpack другой реализацией. Со своей стороны, очевидно, предлагаю python реализацию через [onec_dtools](https://github.com/Infactum/onec_dtools). Собственно ей я и проверил факт корректной сборки, если не применять сжатие. Либо перспективный [вариант ](https://github.com/dmpas/gonpack)на go. Но на сколько мне ясно, он пока толком не был протестирован.

**Comment by dmpas** [comment]
Перспективный вариант - это когда работа с двоичными данными в 15-й версии Односкрипта появится :)

**Comment by artbear** [comment]
>Замена v8unpack другой реализацией. Со своей стороны, очевидно, предлагаю python реализацию через onec_dtools. 

ИМХО питон не айс, не хотелось бы еще и его устанавливать.
Вроде бы мы от него практически избавились уже год как :) я про оскрипт-проекты

**Comment by pumbaEO** [comment]
@artbear не надо на python гнать, мы отказались от python из-за трудностей по установке питона на серверно-виртуальных  виндовых машинках.

**Comment by artbear** [comment]
@pumbaEO не только из-за этого отказались, главное, все-таки - это перевод всех скриптов и приложений на 1скрипт.

**Comment by artbear** [comment]
@nixel2007 precommit1c также нужно подпилить, верно?

**Comment by nixel2007** [comment]
@artbear да вроде никто не жаловался. но из известных мне случаев на чистых исходниках от прекоммита работали только я и Женя Павлюк, оба на управляемых формах.

**Comment by artbear** [comment]
@nixel2007 Проблема вот в чем.
Ты допиливал прекоммит1с для сборки из исходников, мы заявили в доке, что сборка есть и работает.
Сейчас выясняем, что сборка иногда может работать неверно.
ИМХО эту проблему нужно устранить.

Для этого что нужно поправить в прекоммит1с ?? /cc @Infactum @dmpas @nixel2007 
Никита, может быть, ты сможешь поправить?

**Comment by nixel2007** [comment]
@artbear в прекоммите идет работа только с внешними обработками. при вызове v8unpack не передается флагов inflafe/deflate изначально.

**Comment by Infactum** [comment]
@artbear эта проблема актуальная только там, где сначала производится выгрузка средствами конфигуратора, а потом дополнительно form.bin распаковывается v8unpack. Вот если после этого надо аналогичным образом собирать, то команды вызова v8unpack надо подправить, добавив опцию `-nopack`. На сколько это актуально в precommi1c сейчас - не знаю. Я на допиленной python версии сижу)

**Comment by artbear** [comment]
Сборку конфигураций из исходников с толстыми формами никто не делал :) поэтому и тестов соответствующих нет, а другие тесты есть.
Разборкой пользуемся давно, а вот сборка неудобна, медленна и т.п.

Например, как уже отметил @nixel2007, precommit1c разбирает/собирает исходники внешних обработок, а не конфигурации.

**Comment by artbear** [comment]
Выполнено еще в декабре
