### ISSUE TITLE
Команда для произвольного запуска в режиме Конфигуратор

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/vanessa-runner#270]
Нужна отдельная команда для произвольного запуска в режиме Конфигуратор:
1) использование vanessa-runner для случаев, под которые не существует отдельных команд. например, отчет о сравнении (comparecfg)
2) в некоторых случаях в "полуавтоматических" скриптах требуется после автоматических действий просто запустить конфигуратор интерактивно для дальнейших ручных действий.
это было бы удобно делать всё в контексте одного инструмента
например, создать базу - обновить из хранилища - захватить какие-то объекты - открыть конфигуратор базы

**Comment by 1cgh** [comment]
> > создать базу - обновить из хранилища - захватить какие-то объекты - открыть конфигуратор базы
> 
> @1cgh насколько я понимаю, все указанные операции уже есть в ванесса-раннер.
> 
> одно но - для каждой команды запускается и завершаетсяотдельный процесс Конфигуратора

@artbear тут имелось в виду, что есть ряд команд, которые уже реализованы в vb, а просто запуска конфигуратора - нет. т.е. вместо скрипта из нескольких последовательных вызовов разных команд vb сейчас придется в конце добавлять просто вызов .exe 1С с параметрами запуска без удобной обертки. про designer спасибо, посмотрю

**Comment by 1cgh** [comment]
> > использование vanessa-runner для случаев, под которые не существует отдельных команд. например, отчет о сравнении (comparecfg)
> 
> ИМХО тут сложно.
> не хочется дублировать все параметры 1С
> 
> приведи возможный пример запуска такой еще не реализованной команды через vanessa-runner

и не надо дублировать все параметры. команда произвольного запуска конфигуратора отдельными параметрами принимает общие параметры запуска (включая возможность чтения из --settings) и отдельный строковый параметр со всей остальной произвольной частью команды.
т.е. например, что-то вроде

`vrunner designer --settings myenv.json --additional "/CompareCfg –FirstConfigurationType MainConfiguration –SecondConfigurationType File -SecondConfigurationKey d:\test.cf -MappingRule ByObjectIDs -ReportType Brief -ReportFormat txt -ReportFile d:\comparecfg.txt"`

**Comment by 1cgh** [comment]
@artbear т.е. мы получаем возможность выполнять те команды конфигуратора, которые не реализованы отдельными командами vrunner, но при этом имея упрощенную обвязку по генерации остальных параметров запуска, которую предоставляет vrunner

**Comment by artbear** [comment]
Ага, так стало понятнее.

да, можно и нужно расширить designer возможностью доп.параметров

**Comment by artbear** [comment]
deПроверил, пока команда `designer` все-таки доступна через `runner-old`, а не через `vrunner`

**Comment by artbear** [comment]
Ура, наконец-то удалось сделать.
