### ISSUE TITLE
Команда session lock  не устанавливает дату окончания блокировки

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/vanessa-runner#273]
При выполнении session lock предусмотрена возможность установки только даты начала действия блокировки.
При этом может возникать следующая ситуация:
* в свойствах базы уже была установлена дата **окончания** блокировки, но блокировка сеансов выключена.
* session lock устанавливает дату начала блокировки, которая больше установленной даты окончания блокировки.
* session lock включает блокировку сеансов.
* блокировка не работает из-за того, что дата окончания блокировки уже наступила.

Предложения:
ввести параметр-флаг для очистки даты окончания блокировки. При наличии параметра session lock будет устанавливать дату начала блокировки и очищать дату окончания блокировки.

**Comment by artbear** [comment]
Выполнено
