### ISSUE TITLE
Добавить возможность указания формата вывода отчёта xunit

### ISSUE THREAD

**Issue by realMaxA** [silverbulleters/vanessa-runner#28]
Сейчас для выполнения unit тестов можно/нужно указать каталог с тестами, путь к обработке тестирования и путь, по которому будет выведен результат тестирования.

Возможности вывести отчёт в формате, отличном от "ГенераторОтчетаJUnitXML" (указано непосредственно в коде) сейчас нет. Но иногда требуется отчёт в ином формате.

Нужно добавить возможность указания формата генерируемого xunit-отчёта. По умолчанию пусть будет "ГенераторОтчетаJUnitXML".

**Comment by realMaxA** [comment]
Также стоит предусмотреть возможность реализации https://github.com/xDrivenDevelopment/xUnitFor1C/issues/666

**Comment by artbear** [comment]
https://github.com/xDrivenDevelopment/xUnitFor1C/issues/666 доработан.

Решено? Закрываем?

@realMaxA Если у тебя все нормально сформировалось, закрывай свою заявку, пожалуйста.

**Comment by artbear** [comment]
>@realMaxA получил на CI отчёты дымового xUnitFor1C теста одновременно в junit и allure форматах при помощи subj
