### ISSUE TITLE
Некорректное описание команды createrepouser в runner help

### ISSUE THREAD

**Issue by ovcharenko-di** [silverbulleters/vanessa-runner#291]
команда runner help выводит некорректное описание для команды createrepouser

**Comment by ilgizvip** [comment]
ох уж этот копипаст
```
bindrepo         -      Подключение ИБ к хранилищу конфигурации 1С.

createrepouser   -      Подключение ИБ к хранилищу конфигурации 1С.
```

**Comment by ilgizvip** [comment]
Лучше всего будет создать **pullrequest**

**Comment by ovcharenko-di** [comment]
@ilgizvip уже исправлено, https://github.com/silverbulleters/vanessa-runner/pull/292
