### ISSUE TITLE
Потерялась функциональность группировки по режимам проверки

### ISSUE THREAD

**Issue by VladFrost** [silverbulleters/vanessa-runner#307]
ФУНКЦИОНАЛЬНОСТЬ
В версии 1.6.0 можно было группировать отчеты по выбранному режиму проверки и таким образом выполнять triage (сортировку) ошибок.

КОГДА я запускаю vrunner, например, следующими командами:
```
vrunner syntax-check --groupbymetadata --junitpath IncorrectReferences.xml --mode -IncorrectReferences
vrunner syntax-check --groupbymetadata --junitpath SyntaxCheck.xml --mode -SyntaxCheck
vrunner syntax-check --groupbymetadata --junitpath ExtendedModulesCheck.xml --mode -ExtendedModulesCheck
```

ТОГДА я получаю отчеты, сгруппированные по видам проверок:
```
CheckConfig.IncorrectReferences
CheckConfig.SyntaxCheck
CheckConfig.ExtendedModulesCheck
```

Данная функциональность реализована была в этой строке:
https://github.com/silverbulleters/vanessa-runner/commit/dfe3f7a75ef0b8e19979cb79285f12c57ea9ae2c#diff-d7c8ed751dec6f48790374319180b368L210

Сейчас эта группировка пропала, и все проверки попадают в группу "CheckConfig.base"
https://github.com/silverbulleters/vanessa-runner/commit/dfe3f7a75ef0b8e19979cb79285f12c57ea9ae2c#diff-d7c8ed751dec6f48790374319180b368R150 

@artbear @theshadowco помогите, пожалуйста, восстановить функциональность и написать feature-файл, чтобы эта функциональность больше не ломалась.

**Comment by artbear** [comment]
Выполнено в #318 

@VladFrost Большущее спасибо!
