### ISSUE TITLE
Сборка констант

### ISSUE THREAD

**Issue by ghost** [silverbulleters/vanessa-runner#311]
Пользуюсь версией 1.7.0.

Суть в том, что компиляция .cf не выгружает новые константы, а также изменения новых констант. Измененеия констант, которые были в конфигурации, компилируются отлично.

Срочный момент

@artbear @igostv

**Comment by allustin** [comment]
Платформа 8.3.12.1714. Возможно, дело в ней, но я еще не тестил ручную выгрузку.

принял @g-ones в Intercom

**Comment by SaDiSST** [comment]
Здравствуйте. Собственно, я автор репорта.
Собирал вчера из коммитов .cf, обнаружил такую штуку.
Сейчас проверил ручную выгрузку - всё отрабатывает корректно.

-  У константы АвтоматическиНастраиватьРазрешенияВПрофиляхБезопасности изменен тип Булево -> Булево, ЛюбаяСсылка
-  _ТестоваяСсылочнаяКонстанта -> является тестовой для проверки, тип Ссылка на справочник
-  Т_ГруппаУслугПоДоставке -> то же самое, но тест с нею не планировался



Ручной режим:
![01](https://user-images.githubusercontent.com/12616886/64321285-b69b6180-cfd9-11e9-9c70-bd51ee7ae6bf.PNG)

Автоматический, собранный через vrunner compile --v8version 8.3.12.1714 -s %CD% -o %cf_dir%\ut_%DATE%.cf:
![02](https://user-images.githubusercontent.com/12616886/64321530-227dca00-cfda-11e9-8bdf-4b2670b1e81c.PNG)

**Comment by artbear** [comment]
тут вопрос к платформе 1С, видимо, в 8.3.12.1714 есть некий косяк.

попробуй собрать на другой платформе 1С, более новой.

**Comment by artbear** [comment]
@SaDiSST еще стоит проверить, точно ли в исходниках -s %CD% "правильное" состояние.

возможно, там старые исходники, в которых нет обсуждаемых изменений

**Comment by artbear** [comment]
закрываю, т.к. нет ответа почти 2 месяца от @SaDiSST 

и проблема, скорее всего, платформенная от 1С.
