### ISSUE TITLE
Отсутствует зависимость add

### ISSUE THREAD

**Issue by Gisborn** [silverbulleters/vanessa-runner#325]
При установке vanessa-runner через opm не ставится add, однако при попытке выполнить runner help - ругается на отсутствие файла

После установки add, работает корректно

C:\>opm install vanessa-runner
ИНФОРМАЦИЯ - Скачиваю файл: vanessa-runner.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет vanessa-runner
ИНФОРМАЦИЯ - Регистрация приложения: runner
ИНФОРМАЦИЯ - Регистрация приложения: vrunner
ИНФОРМАЦИЯ - Регистрация приложения: vanessa-runner
ИНФОРМАЦИЯ - Регистрация приложения: runner-old
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <logos> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <logos> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <cmdline> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <cmdline> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <tempfiles> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <tempfiles> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <asserts> из каталога локальных зависимостей
ИНФОРМАЦИЯ - Устанавливаю зависимость: <v8runner> из каталога локальных зависимостей
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <json> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <json> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <1commands> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <1commands> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <1bdd> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <1bdd> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <fs> из каталога локальных зависимостей
ИНФОРМАЦИЯ - Устанавливаю зависимость: <ParserFileV8i> из каталога локальных зависимостей
ИНФОРМАЦИЯ - Устанавливаю зависимость: <v8storage> из каталога локальных зависимостей
ИНФОРМАЦИЯ - Устанавливаю зависимость: <v8unpack> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <v8unpack> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <opm> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <opm> уже установлен. Пропускаем.

C:\>runner help
ОШИБКА - Не удалось выполнить команду xunit для класса КомандаТестирование_xUnitFor1C
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runner\src\Модули\ОбщиеМетоды.os / Ошибка в строке: 361 / Внешнее исключение (System.IO.DirectoryNotFoundException): Could not find a part o
f the path 'C:\Program Files (x86)\OneScript\lib\add\ospx\addospx.os'.}

**Comment by artbear** [comment]
@Gisborn ванесса-раннер может работать во взаимосвязи с пакетом ванесса-адд.
но сейчас в инфраструктуре библиотек/приложений oscript нет возможности указать, что одно приложение использует другое приложение без задваивания приложений (
поэтому нужно использовать/ставить оба пакета.

**Comment by EvilBeaver** [comment]
Кажется, нужно переоткрыть, т.к. проблема решаема

**Comment by morohon** [comment]
Проблема осталась при установке vanessa-runner v. 1.9.0 через opm. Детально описывали в tg: https://t.me/oscript_library/15767

**Comment by goro781** [comment]
поставил все пакеты (Vrunner, vanessa-add) выдает ошибку КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\src\Классы\КомандаТестирование_xUnitFor1C.os / Ошибка в строке: 200 / Внешнее исключение (System.ArgumentException): Путь имеет недопустимую форму.} при запуске команды xunit. как можно с ней бороться? Не могу найти информацию по этой ошибке, помогите разобраться пожалуйста.
