### ISSUE TITLE
Ошибка "Нет ошибок" при успешном прохождении синтаксического контроля

### ISSUE THREAD

**Issue by TheDemonCat** [silverbulleters/vanessa-runner#334]
Ошибка наблюдается в версии develop, на отчетах junit и allure
![image](https://user-images.githubusercontent.com/26283990/72234012-ee07c380-35f4-11ea-9a28-f11f01bd05d6.png)

Причина - [тут ](https://github.com/silverbulleters/vanessa-runner/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81%D0%B0.os#L242) не отрабатывается событие, что в переменной ```ЛогПроверкиИзКонфигуратора``` может приехать текст "Ошибок не обнаружено"
![image](https://user-images.githubusercontent.com/26283990/72234108-8dc55180-35f5-11ea-8148-56d3a18ded43.png)

![image](https://user-images.githubusercontent.com/26283990/72234091-738b7380-35f5-11ea-9286-2db9364759ce.png)

![image](https://user-images.githubusercontent.com/26283990/72234210-19d77900-35f6-11ea-9959-b262e9ead85a.png)

Предлагаемое исправление:
![image](https://user-images.githubusercontent.com/26283990/72234133-c107e080-35f5-11ea-8044-eb31b6b02672.png)

Тогда проблема уходит

![image](https://user-images.githubusercontent.com/26283990/72234218-26f46800-35f6-11ea-9abb-7cb6c6d2e19d.png)

**Comment by VladFrost** [comment]
Похоже, это исключительно редкий случай, когда ошибок не обнаружено )

**Comment by artbear** [comment]
и у нас и у активного клиента также видно. баг недавно внесли )

**Comment by artbear** [comment]
Выполнено в https://github.com/silverbulleters/vanessa-runner/pull/335

@TheDemonCat Большое спасибо!
