### ISSUE TITLE
При сборке внешнего механизма из исходников, итоговый файл сохраняется по пути, отличающемуся от требуемого

### ISSUE THREAD

**Issue by Pistolierro** [silverbulleters/vanessa-runner#341]
runner.bat compileepf "C:\\repo\\ОбработкаТест" "C:\\Обработки\\Сборка"
"C:\\repo\\ОбработкаТест" - папка с исходниками внешней обработки;
"C:\\Обработки\\Сборка" - целевая папка, куда должен быть сохранен файл обработки "*.epf"

Ошибка в том, что целевой файл будет собран и сохранен в папку "C:\\Обработки", а должен в "C:\\Обработки\\Сборка"

**Comment by artbear** [comment]
Выполнено в #342 и #345
