### ISSUE TITLE
в именах переменных среды символ дефиса не корректно работает в сборочных линиях

### ISSUE THREAD

**Issue by TheDemonCat** [silverbulleters/vanessa-runner#343]
такой блок в дженкинсе работать не будет:
environment{
RUNNER_storage-user = "user"
RUNNER_storage-pwd = "СекретныйПароль"
}
но, тут https://github.com/silverbulleters/vanessa-runner/blob/develop/src/main.os#L40 заявлены именно такие переменные среды
И вообще не совсем корректные имена. Обычно они пишутся заглавными буквами.

Предлагаю дополнить структуру новыми параметрами, продублировав текущие.

**Comment by artbear** [comment]
Да, согласен с новыми именами параметров. Сделаешь ПР?
@TheDemonCat

**Comment by TheDemonCat** [comment]
Да.

**Comment by artbear** [comment]
исправлено в https://github.com/silverbulleters/vanessa-runner/pull/346
