### ISSUE TITLE
Синтаксическая проверка при отсутствии ошибок отмечает jUnit тест как упавший

### ISSUE THREAD

**Issue by yukon39** [silverbulleters/vanessa-runner#344]
Синтаксическая проверка  при отсутствии ошибок отмечает jUnit тест как упавший.

vanessa-runner: 1.9.0
oscript: 1.2.0.92 x64
Платформа: 8.3.13.1644 x32
Командная строка: `vrunner syntax-check --junitpath out/syntax-check.xml --ibconnection "/Sserver\database" --v8version 8.3.13.1644 --mode -ThinClient -Server -ExternalConnectionServer`

После запуска формируется syntax-check.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites name="CheckConfig.base" tests="1" failures="1" skipped="0" time="177">
    <testsuite name="CheckConfig.base">
        <properties/>
        <testcase classname="CheckConfig.base.Ошибка" name="Синтаксическая проверка конфигурации">
            <failure type="ERROR" message="Ошибок не обнаружено&#xA;"/>
        </testcase>
    </testsuite>
</testsuites>
`

**Comment by artbear** [comment]
уже есть ишуз https://github.com/silverbulleters/vanessa-runner/issues/334

**Comment by artbear** [comment]
выполнено в https://github.com/silverbulleters/vanessa-runner/pull/335
