### ISSUE TITLE
Пропущена библиотека ФС в \src\Модули\ГенерацияОтчетов.os 

### ISSUE THREAD

**Issue by TheDemonCat** [silverbulleters/vanessa-runner#347]
{Модуль C:\Program Files\OneScript\lib\vanessa-runner\src\Модули\ГенерацияОтчетов.os / Ошибка в строке: 151,151 / Неизвестный символ: ФС}

**Comment by artbear** [comment]
Выполнено в https://github.com/silverbulleters/vanessa-runner/pull/348
