### ISSUE TITLE
Концепция? Неудобный механизм изменений текстовых файлов, отличных от внешних обработок

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#37]
У меня есть репозиторий, в нем ведутся исходники и обработок, и конфигурации, и других файлов (например, документация в режиме markdown, и скрипты в виде cmd- и -os-файлов)
В каталоге .\build (игнорируется гитом) организована рабочая копия данных.
В каталоге .\tools есть нужные мне скрипты.

Теперь получается дублирование данных:
+ в каталоге .\build\out\tools появляются копии скриптов из каталога .\tools
+ я изменяю один из скриптов в каталоге .\tools, как привык при работе в других репозиториях 
+ выполняю коммит файлов из каталога .\tools
+ выполняю изменения внешней обработки из каталога .\build\out\МояОбработка.epf
+ выполняю команду `runner.os decompileepf ... ` и `runner.os decompilecurrent ... ( выполняю decompile.bat)
+ и гит показывает мне, что мои свежие изменения откатываются, т.е. возвращаются старые, до коммита.

Проблема в том, что скрипты из каталога .\tools переписываются из  .\build\out\tools и заменяются.

ИМХО это очень большой сюрприз и неприятность.
Особенно, если не сделаешь коммит своих текстовых файлов, я уже успел и на этот вариант нарваться :(

Предлагаю решить концептуально :) - в каталоге  .\build\out мы храним только исходники обработок + файлы конфигурации или всех прочих файлов?

Последний вариант не гуд, т.к. есть дублирование файлов и будет реальная путаница.
Мое предложение - в каталоге  .\build\out мы храним только исходники обработок + файлы конфигурации

/cc @pumbaEO @allustin @nixel2007

**Comment by nixel2007** [comment]
Ты немного неверно понял концепцию.
Если используется раннер, то надо работать с build/out как рабочим
каталогом. А после внесения изменений делать вызывать скрипт разбора на
исходники.
Плюс дополнительно там лежит watch.sh/bat, который позволяет автоматически
собирать/разбирать все файлы.

23 декабря 2016 г., 18:37 пользователь Artur Ayukhanov <
notifications@github.com> написал:

**Comment by artbear** [comment]
ИМХО это очень неудобно.
При работе в других языках (C# и т.п.) и тех же репозиториях os-скриптов у нас исходники находятся в одном месте, а не дублируются в двух местах :(
Это создает реальные проблемы для пользователя !

**Comment by artbear** [comment]
Далее - watch предназначен для слежения за бинарниками. 
Зачем следить за текстовиками, дублировать работу гит?
гит прекрасно разбирается, когда меняются текстовые исходники

**Comment by artbear** [comment]
Реально народ будет косячить и использовать разные файлы.
Как-то не очень юзабельно получается.

**Comment by artbear** [comment]
Планирую доработки продукта согласно уже созданным issue.
Хотел бы понимать, куда двигаться дальше.

Жду ответа.

**Comment by pumbaEO** [comment]
В build/out я копирую все, т.к. есть еще проблема с указанием настроек (откуда запускаем epf и относительные пути), с feature файлов, которые по пути и имени определяют прироритет и ищут в папке step_definitons бинарные обработки, что-бы их подключить.

**Comment by artbear** [comment]
>есть еще проблема с указанием настроек (откуда запускаем epf и относительные пути), с feature файлов, которые по пути и имени определяют прироритет и ищут в папке step_definitons бинарные обработки, что-бы их подключить.

@pumbaEO Вот это я не понял.
Фича-файлы я буквально только что добавил в проект, их же раньше не было :)
поясни, плиз.

**Comment by nixel2007** [comment]
@artbear фича-файлы не данного проекта, а проекта с которым ты работаешь - конфа с фичами для VB например.

**Comment by artbear** [comment]
А можете указать на пример подобной фичи и ее реализации?
хочу понять, как решается вопрос с указанием путей в фиче и ее реализации.

**Comment by nixel2007** [comment]
Абсолютно любой проект.
Все содержимое репа копируется в build/out. Работаешь с VB - указываешь как каталог фич каталог build/out/features. Все остальное подхватывается само. Никаких доработок со стороны фич или инструментов не требуется.

**Comment by artbear** [comment]
закрываю как устаревший - в Vanessa.ADD реализован хороший вариант, без лишних каталогов
