### ISSUE TITLE
Синхронизировать с git исходники из файла базы.

### ISSUE THREAD

**Issue by alekckuc** [silverbulleters/vanessa-runner#46]
Приветствую коллеги.
Я только начинаю интересоваться темой групповой разработки через git , но хранилища использую довольно давно (накушался по полной ну вы в курсе ....).
Интересует функция быстрой выгрузки исходников прямо из базы. Суть в том, что в процессе работы над проектами бывает необходимо  внести мелки правки в проект и часто это происходит в режиме онлайн прямо на продуктиве. Хотелось бы иметь утилиту которая  сделает синхронизацию исходников с git  желательно без участия специалиста выполняющего правки, если есть возможность  как то отловить факт изменения конфигурации  и по этому событию запустить синхронизацию.
Подскажите какие инструменты сообщества лучше использовать для решения задачи ? И как это лучше сделать ?

**Comment by nixel2007** [comment]
Синхронизация именно базы, но не хранилища?

**Comment by alekckuc** [comment]
Да не хранилище, а конфигурацию базы из базы. Предполагаю что без какойнибудь фоновой выгрузки в CF не обойтись, но делать это в одном "пакете" . С хранилищем очень много всяких траблов, я бы вообще ушел от их использования

**Comment by nixel2007** [comment]
Можно настроить регламентную выгрузку, либо настроить триггер на уровне sql
Не забывайте, что выгрузка конфы требует монопольного доступа в конфигуратор, то есть выгружать таким образом конфу прямо во время активной работы будет не очень удобно

**Comment by alekckuc** [comment]
Да про монопольный доступ понятно. Предполагается что "полезный"  запуск будет уже после окончания работы с конфигуратором. Можно и по кнопке. Но как бороться с "забывчивостью"  лучше чтоб это происходило автоматически, по расписанию не очень эффективно. Триггер хорошая идея спасибо, для SQL баз. остаются файловые.
