### ISSUE TITLE
Встроенная справка врет

### ISSUE THREAD

**Issue by EvilBeaver** [silverbulleters/vanessa-runner#50]
Запуск xunit по документации и по файлу examples/xunit.bat невозможен.

В командной строке выводятся параметры запуска. Для xunit они некорректные. Пример в каталоге examples также некорректен.

**Comment by nixel2007** [comment]
Вроде бы @realMaxA запускал xunit из раннера?

**Comment by artbear** [comment]
Да, Женя менял названия параметров.
Нужно исправить доку и примеры.
Примеры вообще сильно устаревшие

**Comment by realMaxA** [comment]
Встроенная справка subj никакого отношения к действительности не имеет. Нужно смотреть код. Батники, если они были просто перемещены из tools/ в examples/ без переработки, вообще заведомо нерабочие.
Говорят, что за правильными батниками надо ходить в vanessa-behavior-new.

**Comment by nixel2007** [comment]
По бехавиору тоже справка врет.
Может перетащить команду help из шаблона библиотеки от @EvilBeaver ?
Там справка автоматически собирается по данным парсера.

**Comment by artbear** [comment]
>Может перетащить команду help из шаблона библиотеки от @EvilBeaver ?

Я в 1bdd сделал это.
Можешь оттуда забрать, должно легко лечь на сабж

**Comment by pumbaEO** [comment]
Пока проблему купировал, но лучше конечно справку генерить автоматом.

**Comment by realMaxA** [comment]
Значит ли то, что закрыт данный issue, что встроенная справка выдаёт теперь верную информацию?

**Comment by nixel2007** [comment]
@realMaxA не совсем. Я просто слил какой-то из коммитов, у которого было написано Фикс 50. Для полной уверенности в справке нужно чуть менять архитектуру приложения (перевод на апп тэмплейт, который обсуждается где-то рядом)

**Comment by realMaxA** [comment]
Собсно я сейчас этим и занимаюсь )

**Comment by artbear** [comment]
@realMaxA Отлично.
Надеюсь, ты возьмешь наши последние исправления за сегодня.

**Comment by realMaxA** [comment]
Да.
Но у меня в любом случае есть вопрос, как это всё тестировать? Размещение процедур перетасовано полностью, разнесено по файлам, etc.

**Comment by nixel2007** [comment]
@realMaxA test first.
сначала пишем тест, проверяем, что он работает, потом рефакторим.

**Comment by realMaxA** [comment]
Тест пишем как? Через существующий фреймворк 1ctestrunner или можно обойтись просто запуском команд из командной строки?
Как тестировать в связке с заданием параметров в переменных окружения и в файле конфигурации? Надо ж проверить, что все параметры подставляются правильно!
Как проверять результат выполнения команд? Нужно ж ещё проверить, что команда не только отработала, но и отработала правильно!
Как быть с тем, что init.os перестанет существовать и обе его команды переедут в runner.os?
Что делать, если есть желание переименовать команды "init-dev" и "update-dev" из init.os в "init-db" и "update-db" соответственно?

**Comment by artbear** [comment]
при глобальном рефакторинге нужно максимально сдерживать себя и не добавлять новую функциональность, иначе очень сложно разбираться в изменениях.
Например, не нужно менять наименования команд.

изменение вызова init.os на runner.os это осознанное изменение, нужно просто это учесть.

С тестами все очень непросто. Конечно, тесты через 1testrunner или 1bdd.
никакой другой запуск из ком.строки не решает проблему тестирования.

**Comment by artbear** [comment]
я обычно при глобальном рефакторинге записываю отдельный список задач, которые нужно доработать, и уже после выполнения всех изменений и получения стабильного результата перехожу к их решениям.
Предлагаю завести отдельный ишуз на рефакторинг (вроде бы он есть) и в нем отмечать то, что нужно доработать.
потом из этого списка сделаем отдельные ишузы или PR, которые доработаем после приемки основного рефакторинга.

**Comment by artbear** [comment]
Уже исправлено
