### ISSUE TITLE
Проверка существования v8unpack перед запуском основной программы

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#55]
Предлагаю добавить проверку существования v8unpack перед запуском основной программы.
Например, просто вызов v8unpack и проверка отсутствия ошибки The system cannot find the file specified или Не удается найти указанный файл

В продолжение https://github.com/silverbulleters/vanessa-runner/issues/21

**Comment by pumbaEO** [comment]
Как бы еще добавить какой-то признак, что не работаем чисто в УФ и нам даже если вдруг и встретится ОФ форма, то ее не надо распаковывать?

**Comment by artbear** [comment]
Выполнено
