### ISSUE TITLE
Флаг запуска в тонком клиенте и толстом клиенте

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/vanessa-runner#6]
Иногда необходимо запускать VB и xUnit в тонком клиенте - например, в конфигурации запрещен запуск толстого клиента.
Хочется иметь еще флаг-параметр командной строки, который позволит запускать 1с в тонком клиенте.

Даже заготовочка уже есть: https://github.com/silverbulleters/vanessa-runner/blob/develop/tools/runner.os#L571

**Comment by artbear** [comment]
Учесть необходимость запуска в толстом клиенте

**Comment by nixel2007** [comment]
Он уже есть. по крайней мере для xunit и vb - `--ordinaryapp`

**Comment by nixel2007** [comment]
Только он почему-то не Параметр-флаг, а именованный параметр, поэтому надо указывать `--ordinaryapp true`

**Comment by artbear** [comment]
Посмотрели с Никитой, есть недочеты.
Добавили описание в #7

**Comment by artbear** [comment]
Выполнено. Проверено на CI TFS
