### ISSUE TITLE
Запуск в обычном приложении

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-runner#7]
Хотелось бы иметь возможность запускать xunit и VB в обычном приложении, чтобы тестировать конфигурации на обычных формах

**Comment by pumbaEO** [comment]
Тут наверное надо доп.ключ делать, для возможности передачи как параметр.

**Comment by pumbaEO** [comment]
Добавил параметр --ordinaryapp 1 в случаи настроек пользователя, можно дополнительно указать --additional "/RunModeOrdinaryApplication "

**Comment by nixel2007** [comment]
OrdinaryApp - это обычное приложение. А сейчас запускается управляемое приложение в толстом клиенте.

Для xUnit - параметр OrdinaryApp не учитывается (по крайней мере в мастере)
ЗапуститьВРежимеПредприятия - не учитывается вообще.

Надо доделать/переделать :(

**Comment by artbear** [comment]
Выполнено. Проверено на CI TFS
