### ISSUE TITLE
При прогоне xUnit использовать файл кода возврата для определения правильного кода возврата

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-runner#70]
Это стало возможно благодаря решению https://github.com/xDrivenDevelopment/xUnitFor1C/issues/685

**Comment by nixel2007** [comment]
В раннер.ос? странный коммит. не потеряется?

**Comment by artbear** [comment]
да, странно это.
чего делать?

**Comment by nixel2007** [comment]
я не понимаю, откуда он вообще появился. самое простое - руками перенести
черри-пикать не получится, так как файлы разные.

**Comment by artbear** [comment]
В коде девелоп этот код есть, так что все в порядке
