### ISSUE TITLE
Ошибка при запуске Xunit

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-runner#8]
ОШИБКА - 
20.08.2016 12:20:17: ОШИБКА - {Модуль E:\slave-5\workspace\ppt\workspace@script\tools\vanessa-runner\tools\runner.os / Ошибка в строке: 664 / ЗапуститьТестироватьЮнит}

Происходит потому, что не может удалить каталог в строке ВременныеФайлы.УдалитьФайлы(КаталогВременнойИБ);

Хотя строка подключения вообще не подразумевает использование временного каталога

**Comment by artbear** [comment]
@viskvortsov ИМХО не актуально.
Закрываю.
