### ISSUE TITLE
runner --help {Метод объекта не обнаружен (ВывестиСправкуПоКомандам)}

### ISSUE THREAD

**Issue by ivan-kovtun** [silverbulleters/vanessa-runner#97]
Устанавливаю vanessa-runner
opm install vanessa-runner

Запускаю runner --help (или без параметров)
Получаю 
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runner\src\Классы\КомандаСправкаПоПараметрам.os / Ошибка в строке: 48 / Метод объекта не обнаружен (ВывестиСправкуПоКомандам)}

**Comment by nixel2007** [comment]
Какая версия? На 0.8.3 пробую, работает

**Comment by ivan-kovtun** [comment]
0.8.3
PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> runner
vanessa-runner v0.8.3
08.04.2017 18:21:18: ОШИБКА - Некорректные аргументы командной строки
08.04.2017 18:21:18: КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runner\src\Классы\КомандаСправкаПоПараметрам.os / Ошибка в строке: 48 / Метод объекта не обнаружен (ВывестиСправкуПоКомандам)}

**Comment by artbear** [comment]
@ivan-kovtun сначала сделай opm install opm
затем opm install vanessa-runner

**Comment by artbear** [comment]
У тебя старая версия одной из библиотек, которые нужны ванесса-раннер.

**Comment by ivan-kovtun** [comment]
Не помогло к сожалению

> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> opm install opt
> ИНФОРМАЦИЯ - Скачиваю файл: opt.ospx
> Ошибка установки пакета opt <404>
> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> opm update opm
> ИНФОРМАЦИЯ - Скачиваю файл: opm.ospx
> ИНФОРМАЦИЯ - Устанавливаю пакет opm
> ИНФОРМАЦИЯ - Устанавливаю зависимость: fs
> ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
> ИНФОРМАЦИЯ - Устанавливаю зависимость: cmdline
> ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
> ИНФОРМАЦИЯ - Регистрация приложения: opm
> ИНФОРМАЦИЯ - Установка завершена
> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> opm update vanessa-runner
> OneScript Package Manager v0.9.4
> ИНФОРМАЦИЯ - Скачиваю файл: vanessa-runner.ospx
> ИНФОРМАЦИЯ - Устанавливаю пакет vanessa-runner
> ИНФОРМАЦИЯ - Ошибка установки пакета <vanessa-runner>: Обнаружена устаревшая версия движка OneScript.
> Требуемая версия: 1.0.16
> Текущая версия: 1.0.14.195
> Обновите OneScript перед установкой пакета
> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> runner
> vanessa-runner v0.8.3
> 08.04.2017 21:18:23: ОШИБКА - Некорректные аргументы командной строки
> 08.04.2017 21:18:23: КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runnner\src\Классы\КомандаСправкаПоПараметрам.os / Ошибка в строке: 48 / Метод объекта не обнаружен (ВывестиСправкуПоКомандам)}
> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows>

**Comment by ivan-kovtun** [comment]
Странно... Ругается на "Обнаружена устаревшая версия движка OneScript.
Требуемая версия: 1.0.16
Текущая версия: 1.0.14.195", но это не сам OneScript - он актуален(PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> opm update oscript 
OneScript Package Manager v0.9.4)
Как обновить движок OneScript?

> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> opm install opt
> ИНФОРМАЦИЯ - Скачиваю файл: opt.ospx
> Ошибка установки пакета opt <404>
> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> opm update opm
> ИНФОРМАЦИЯ - Скачиваю файл: opm.ospx
> ИНФОРМАЦИЯ - Устанавливаю пакет opm
> ИНФОРМАЦИЯ - Устанавливаю зависимость: fs
> ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
> ИНФОРМАЦИЯ - Устанавливаю зависимость: cmdline
> ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
> ИНФОРМАЦИЯ - Регистрация приложения: opm
> ИНФОРМАЦИЯ - Установка завершена
> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> opm update vanessa-runner
> OneScript Package Manager v0.9.4
> ИНФОРМАЦИЯ - Скачиваю файл: vanessa-runner.ospx
> ИНФОРМАЦИЯ - Устанавливаю пакет vanessa-runner
> ИНФОРМАЦИЯ - Ошибка установки пакета <vanessa-runner>: Обнаружена устаревшая версия движка OneScript.
> Требуемая версия: 1.0.16
> Текущая версия: 1.0.14.195
> Обновите OneScript перед установкой пакета
> PS D:\dev\gitrepo\vanessa-bootstrap-ik\tools\windows> runner
> vanessa-runner v0.8.3
> 08.04.2017 21:18:23: ОШИБКА - Некорректные аргументы командной строки
> 08.04.2017 21:18:23: КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runner\src\Классы\КомандаСправкаПоПараметрам.os / Ошибка в строке: 48 / Метод объекта не обнаружен ВывестиСправкуПоКомандам)}

**Comment by nixel2007** [comment]
@ivan-kovtun так же, как вы его устанавливали :) с сайта http://oscript.io

**Comment by ivan-kovtun** [comment]
:) Да все ок! Спасибо.
